import type { ExhibitionEvent } from './types';
import { buildExhibitionTopViewHtml } from './exhibitionTopViewExport';

export function buildMetaMallTopViewHtml(event: ExhibitionEvent): string {
  const mallCss = `
.hero{background-image:linear-gradient(135deg,rgba(17,24,39,.94),rgba(120,53,15,.78),rgba(15,23,42,.88))!important}
.badge{background:rgba(251,191,36,.16)!important;border-color:rgba(251,191,36,.38)!important;color:#fde68a!important}
.hall-scene{background:linear-gradient(180deg,rgba(255,247,237,.12),rgba(255,255,255,.045))!important}
.top-floor{background:linear-gradient(135deg,rgba(30,41,59,.94),rgba(67,56,202,.24),rgba(120,53,15,.28)),repeating-linear-gradient(90deg,rgba(251,191,36,.055) 0 1px,transparent 1px 34px),repeating-linear-gradient(0deg,rgba(255,255,255,.032) 0 1px,transparent 1px 34px)!important}
.top-booth{border-radius:14px!important;transform:none!important}
.top-booth.occupied{background:linear-gradient(145deg,var(--hall),rgba(30,41,59,.86))!important}
.brand-roof{border-radius:12px!important}
.brand-name:before{content:"SHOP ";opacity:.65;font-size:8px;letter-spacing:.08em}
.map-structure.pavilion{text-transform:none!important}
.note:before{background:#f59e0b!important}
`;

  return buildExhibitionTopViewHtml(event)
    .replace('</style>', `${mallCss}</style>`)
    .replace(/Interactive Top-View Exhibition/g, 'Tohid Meta Mall Leasing Map')
    .replace(/Online Exhibition Hall/g, 'Tohid Meta Mall')
    .replace(/Exhibition Hall/g, 'Mall Floor')
    .replace(/Top-View Exhibition Floor/g, 'Tohid Meta Mall Shop Map')
    .replace(/Explore the exhibition from above, discover reserved booths, and enter each exhibitor store or catalog\./g, 'Explore Tohid Meta Mall from above, review available and rented shops, and open each tenant store or catalog.')
    .replace(/Click any branded booth to open a smart exhibitor note\. Logos are placed on booth roofs so foreign visitors can scan the hall like a real exhibition map\./g, 'Click any branded shop to open a tenant note. Logos sit on shop roofs so visitors can scan the mall like a premium passage map.')
    .replace(/Total booths/g, 'Total shops')
    .replace(/Reserved booths/g, 'Rented shops')
    .replace(/Open spaces/g, 'Available shops')
    .replace(/All halls/g, 'All floors')
    .replace(/Exhibitor Notes/g, 'Tenant Notes')
    .replace(/Each note gives buyers a quick overview of the exhibitor, products, booth location, and direct store link\./g, 'Each note gives visitors a quick overview of the tenant, products, shop location, and direct store link.')
    .replace(/No reserved exhibitors yet\./g, 'No rented shops yet.')
    .replace(/No exhibitors match your filter\./g, 'No shops match your filter.')
    .replace(/Enter Store \/ Catalog/g, 'Open Shop / Catalog')
    .replace(/Store link coming soon/g, 'Shop link coming soon')
    .replace(/Generated by Tohid Dayhami Export\+ Exhibition/g, 'Generated for Tohid Meta Mall');
}
